#!/bin/bash

DIR="git-auto"

# create directory in home folder if not exist
if [[ ! -d ~/$DIR ]]
then
   mkdir ~/$DIR
fi
# add the folder to path
echo 'export PATH="$HOME/git-auto:$PATH"' >> ~/.bashrc
source ~/.bashrc

# copy the scripts to the git-auto folder
cd commands
for FILE in *;
do
   if [[ ! -e $DIR/$FILE ]]
   then
      cp $FILE ~/$DIR/$FILE
   fi

   # allow execution
   chmod +x ~/$DIR/$FILE
done

echo $'done ✅'