#!/bin/bash

DIR=$PWD

# get the current branch
BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

# print the current branch to console
printf "Current branch: \033[0;32m$BRANCH\n\033[0m"
# copy current branch to clipboard
echo $BRANCH | pbcopy
