#!/bin/bash

# Check out to a difference existing branch since we are trying
# to delete the current branch.
if [[ ! -z $(git ls-remote --heads origin main) ]]; then
    git checkout main
elif [[ ! -z $(git ls-remote --head origin master) ]]; then
    git checkout master
fi

branch=${1}
cur_branch=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

if [[ "$cur_branch" == "$branch" ]]
then
    printf "\033[0;31mCannot delete the branch currently on. Please switch to another branch first!\033[0m\n"
    exit 1
fi

git branch -D "$branch"

existed_in_remote=$(git ls-remote --heads origin ${branch})

if [[ ! -z ${existed_in_remote} ]]; then
    git push origin --delete "$branch"
fi
