#!/bin/bash

DIR=$PWD

echo $VAR

# Add, commit, and push to the current branch
git add .

if [ -z "$1" ]
then
    git commit
else
    git commit -m "${1}"
fi

# only push if commit was successfull
if [[ -z $(git status -s) ]]
then
    BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
    printf "Pushing to branch $BRANCH...\n"
    git push origin $BRANCH
else
    printf "\033[0;31mAborting push since tree is not clean.\033[0m\n"
fi
