#!/bin/bash

BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

# print the current branch to console
printf "current branch: \033[0;32m$BRANCH\n"

# copy current branch to clipboard
echo $BRANCH | pbcopy