#!/bin/bash

DIR=$PWD

# Add, commit, and push to the current branch
git add .
git commit
# only push if commit was successfull
if [[ -z $(git status -s) ]]
then
    BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
    printf "Pushing to branch $BRANCH...\n"
    git push origin $BRANCH
else
    printf "\033[0;31mAborting push since tree is not clean.\033[0m\n"
fi
