#!/bin/bash

DIR=$PWD
# check if a git repo
if [[ -e $DIR/.git ]]
then
# Add, commit, and push to the current branch
    git add .
    git commit

    if [[ -z $(git status -s) ]]
    then
        BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
        printf "Pushing to branch $BRANCH...\n"
        git push origin $BRANCH
    else
        printf "\033[0;31mAborting push since tree is not clean.\n"
    fi
else
    printf "\033[0;31mError: Not a git repository.\n"
fi